spring:
  application:
    name: my-project
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//192.168.1.91:1521/mdjyscs
    username: boot
    password: boot123
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      validationQuery: select 1 from dual
      test-while-idle: true
      filters: stat,wall,slf4j

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

